import fs from 'fs';
import path from 'path';
const AM_BLUE='#1F2A44',AM_MUSTARD='#C8A03A';
function ris(c,p,r){return c.replace(/(["'`])(?:(?!\1|\\).|\\.)*?\1/gs,m=>m.replace(p,r))}
const R=[[/text-emerald-\d{3}/g,`text-[${AM_MUSTARD}]`],[/hover:text-emerald-\d{3}/g,`hover:text-[${AM_MUSTARD}]`],[/bg-emerald-\d{3}\/\[[^\]]+\]/g,`bg-[${AM_BLUE}]/[0.07]`],[/bg-emerald-\d{3}\/\d+/g,`bg-[${AM_BLUE}]/20`],[/bg-emerald-\d{3}/g,`bg-[${AM_BLUE}]`],[/hover:bg-emerald-\d{3}/g,`hover:bg-[${AM_BLUE}]`],[/from-emerald-\d{3}/g,`from-[${AM_BLUE}]`],[/to-emerald-\d{3}/g,'to-[#162033]'],[/border-emerald-\d{3}\/\[[^\]]+\]/g,`border-[${AM_MUSTARD}]/[0.19]`],[/border-emerald-\d{3}\/\d+/g,`border-[${AM_MUSTARD}]/30`],[/border-emerald-\d{3}/g,`border-[${AM_MUSTARD}]`],[/border-l-emerald-\d{3}/g,`border-l-[${AM_MUSTARD}]`],[/shadow-emerald-\d{3}\/\d+/g,'shadow-black/20'],[/shadow-emerald-\d{3}/g,'shadow-black/20'],[/accent-emerald-\d{3}/g,`accent-[${AM_MUSTARD}]`],[/ring-emerald-\d{3}/g,`ring-[${AM_MUSTARD}]`],[/focus:border-emerald-\d{3}\/?\d*/g,`focus:border-[${AM_MUSTARD}]/50`]];
function walk(d){const o=[];for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory()&&!['node_modules','dist','.git'].includes(e.name))o.push(...walk(p));else if(e.isFile()&&/\.(jsx?|tsx?)$/.test(e.name))o.push(p)}return o}
const root=process.cwd(),files=walk(path.join(root,'src'));let ch=0;
for(const f of files){let c=fs.readFileSync(f,'utf-8');const o=c;for(const[p,r]of R)c=ris(c,p,r);if(c!==o){fs.writeFileSync(f,c);console.log('  ✓',path.relative(root,f));ch++}}
const ad=path.join(root,'src/components/analysis/analysisData.js');
if(fs.existsSync(ad)){let t=fs.readFileSync(ad,'utf-8');t=t.replace("emerald: '#10b981'",`emerald: '${AM_MUSTARD}'`);t=t.replace("emeraldDim: '#059669'","emeraldDim: '#A8862F'");fs.writeFileSync(ad,t);console.log('  ✓ analysisData.js palette')}
for(const r of['src/components/auth/LoginScreen.jsx','src/components/auth/ChangePasswordScreen.jsx','src/App.jsx']){const fp=path.join(root,r);if(!fs.existsSync(fp))continue;let t=fs.readFileSync(fp,'utf-8');const o=t;t=t.replace(/>Y</g,'>AMs<');if(t!==o){fs.writeFileSync(fp,t);console.log('  ✓',r,'(Y→AMs)')}}
for(const r of['src/components/layout/Header.jsx','src/components/layout/DesktopSidebar.jsx','src/components/layout/MobileDrawer.jsx']){const fp=path.join(root,r);if(!fs.existsSync(fp))continue;let t=fs.readFileSync(fp,'utf-8');t=t.replace(/\{initial\}/g,'{"AMs"}');t=t.replace(/>YPOTI</g,'>AM Soluciones<');fs.writeFileSync(fp,t);console.log('  ✓',r)}
for(const r of['src/components/auth/LoginScreen.jsx','src/components/auth/ChangePasswordScreen.jsx']){const fp=path.join(root,r);if(!fs.existsSync(fp))continue;let t=fs.readFileSync(fp,'utf-8');t=t.replace(/YPOTI Compras/g,'AM Soluciones');t=t.replace(/Grupo Rural Bioenergia/g,'');t=t.replace(/v3\.0/g,'');fs.writeFileSync(fp,t)}
fs.writeFileSync(path.join(root,'public/favicon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="${AM_BLUE}"/><rect x="2" y="2" width="60" height="60" rx="12" fill="none" stroke="${AM_MUSTARD}" stroke-opacity=".55" stroke-width="2"/><text x="32" y="41" text-anchor="middle" font-family="Inter,system-ui,sans-serif" font-size="22" font-weight="800" fill="${AM_MUSTARD}">AMs</text></svg>`);
console.log('  ✓ favicon.svg');
let html=fs.readFileSync(path.join(root,'index.html'),'utf-8');html=html.replace(/<title>[^<]*<\/title>/,'<title>AM Soluciones</title>');html=html.replace(/YPOTI Compras/g,'AM Soluciones');fs.writeFileSync(path.join(root,'index.html'),html);console.log('  ✓ index.html');
const gc=path.join(root,'src/styles/globals.css');if(fs.existsSync(gc)){let css=fs.readFileSync(gc,'utf-8');if(!css.includes('Playfair Display')){css+='\nbody{font-family:Inter,system-ui,sans-serif}\nh1,h2,h3,.title{font-family:"Playfair Display",serif}\n';fs.writeFileSync(gc,css);console.log('  ✓ globals.css')}}
console.log(`\n✅ ${ch} files updated. Run: npm run build`);
