// ============================================================
// YPOTI — USUARIOS DEFAULT (generado desde grupo-moller.csv)
// Total: 238 empleados
// ============================================================

export const DEFAULT_USERS = [
  {
    "id": "u001",
    "name": "Ronei Ferreira",
    "email": "ronei",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Diretor",
    "avatar": "RF",
    "active": true
  },
  {
    "id": "u002",
    "name": "Ana Beatriz Moller",
    "email": "ana.moller",
    "password": "ypoti2026",
    "role": "admin",
    "establishment": "General",
    "position": "Administradora General",
    "avatar": "AM",
    "active": true
  },
  {
    "id": "u003",
    "name": "Fran Candia",
    "email": "fran.candia",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Regente Salud y Seguridad",
    "avatar": "FC",
    "active": true
  },
  {
    "id": "u004",
    "name": "Liz Fleitas",
    "email": "liz.fleitas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Rrhh y Sso",
    "avatar": "LF",
    "active": true
  },
  {
    "id": "u005",
    "name": "Santiago Jose Maria Campos Ruiz Diaz",
    "email": "santiago.campos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Asistente Trazabilidad",
    "avatar": "SC",
    "active": true
  },
  {
    "id": "u006",
    "name": "Jazmin Tamay",
    "email": "jazmin.tamay",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Regente Medicina Laboral",
    "avatar": "JT",
    "active": true
  },
  {
    "id": "u007",
    "name": "Fabiano Squeruque",
    "email": "fabiano",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente Lusipar, Santa Clara e Ybypora",
    "avatar": "FS",
    "active": true
  },
  {
    "id": "u008",
    "name": "Paulo Becker",
    "email": "paulo",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente Confinamento, Ypoti e Oro Verde",
    "avatar": "PB",
    "active": true
  },
  {
    "id": "u009",
    "name": "Pedro Moller",
    "email": "pedro.moller",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente Santa Maria y Cielo Azul",
    "avatar": "PM",
    "active": true
  },
  {
    "id": "u010",
    "name": "Laura Beatriz Rivas Britez",
    "email": "laura.rivas",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "Ypoti",
    "position": "Encargada Administrativa",
    "avatar": "LR",
    "active": true
  },
  {
    "id": "u011",
    "name": "Elva Marlene Sanchez Cabrera",
    "email": "elva.sanchez",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "Ypoti",
    "position": "Encargada Depósito y Taller",
    "avatar": "ES",
    "active": true
  },
  {
    "id": "u012",
    "name": "Isidro Javier Romero Benitez",
    "email": "isidro.romero",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "Ypoti",
    "position": "Basculero",
    "avatar": "IR",
    "active": true
  },
  {
    "id": "u013",
    "name": "Edison Ronaldo Vega Arce",
    "email": "edison.vega",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "Ypoti",
    "position": "Asistente Confinamento",
    "avatar": "EV",
    "active": true
  },
  {
    "id": "u014",
    "name": "Rodrigo Carvalho",
    "email": "rodrigo.carvalho",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Coordenador Confinamento",
    "avatar": "RC",
    "active": true
  },
  {
    "id": "u015",
    "name": "Alvaro Cuevas",
    "email": "alvaro.cuevas",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Supervisor Confinamento",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u016",
    "name": "Arsenio Alen",
    "email": "arsenio.alen",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Seguridad",
    "avatar": "AA",
    "active": true
  },
  {
    "id": "u017",
    "name": "Moises Lima",
    "email": "moises.lima",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Supervisor Confinamento",
    "avatar": "ML",
    "active": true
  },
  {
    "id": "u018",
    "name": "Anastacio Domingues",
    "email": "anastacio.domingues",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Seguridad Domingo",
    "avatar": "AD",
    "active": true
  },
  {
    "id": "u019",
    "name": "Alberto Vidal Cabañas Fretes",
    "email": "alberto.cabanas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Mecanico",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u020",
    "name": "Cristobal Ortigoza Lopez",
    "email": "cristobal.ortigoza",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Palero",
    "avatar": "CO",
    "active": true
  },
  {
    "id": "u021",
    "name": "Fernando Fretes Mareco",
    "email": "fernando.fretes",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Chofer",
    "avatar": "FF",
    "active": true
  },
  {
    "id": "u022",
    "name": "Herminio Aquino Gonzalez",
    "email": "herminio.aquino",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Palero",
    "avatar": "HA",
    "active": true
  },
  {
    "id": "u023",
    "name": "Julio Ariel",
    "email": "julio.ariel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tractorista John Deere",
    "avatar": "JA",
    "active": true
  },
  {
    "id": "u024",
    "name": "Leonardo Ovelar Ocampos",
    "email": "leonardo.ovelar",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tractorista",
    "avatar": "LO",
    "active": true
  },
  {
    "id": "u025",
    "name": "Oscar Antonio Caballero Vera",
    "email": "oscar.caballero",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Chofer",
    "avatar": "OC",
    "active": true
  },
  {
    "id": "u026",
    "name": "Patrocinio Morel",
    "email": "patrocinio.morel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Palero",
    "avatar": "PM",
    "active": true
  },
  {
    "id": "u027",
    "name": "Pedro Aníbal Ferreira Arguello",
    "email": "pedro.ferreira",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Empleado",
    "avatar": "PF",
    "active": true
  },
  {
    "id": "u028",
    "name": "Robert Zalazar",
    "email": "robert.zalazar",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Palero",
    "avatar": "RZ",
    "active": true
  },
  {
    "id": "u029",
    "name": "Rody Gayoso",
    "email": "rody.gayoso",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tractorista Valtra 194",
    "avatar": "RG",
    "active": true
  },
  {
    "id": "u030",
    "name": "Jefferson Gutierrez Aquino",
    "email": "jefferson.gutierrez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar Mecanico",
    "avatar": "JG",
    "active": true
  },
  {
    "id": "u031",
    "name": "Emerenciano Riquelme Coronel",
    "email": "emerenciano.riquelme",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Encargado Fabrica",
    "avatar": "ER",
    "active": true
  },
  {
    "id": "u032",
    "name": "Edizon Toledo Ocampos",
    "email": "edizon.toledo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Fábrica",
    "avatar": "ET",
    "active": true
  },
  {
    "id": "u033",
    "name": "Pascual Dos Santos",
    "email": "pascual.dos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Fábrica",
    "avatar": "PD",
    "active": true
  },
  {
    "id": "u034",
    "name": "Pio Celso Riquelme Coronel",
    "email": "pio.riquelme",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Fabrica",
    "avatar": "PR",
    "active": true
  },
  {
    "id": "u035",
    "name": "Sebastian Ramos Candia",
    "email": "sebastian.ramos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Fábrica",
    "avatar": "SR",
    "active": true
  },
  {
    "id": "u036",
    "name": "Sixto Ovelar",
    "email": "sixto.ovelar",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar Fábrica (vacaju)",
    "avatar": "SO",
    "active": true
  },
  {
    "id": "u037",
    "name": "Alder Martin Acosta Arevalos",
    "email": "alder.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar de Servicios Generales",
    "avatar": "AA",
    "active": true
  },
  {
    "id": "u038",
    "name": "Bernardo Diaz Villamayor",
    "email": "bernardo.diaz",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar de Servicios Generales",
    "avatar": "BD",
    "active": true
  },
  {
    "id": "u039",
    "name": "Lucio Vega",
    "email": "lucio.vega",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar de Servicios Generales (vacaju)",
    "avatar": "LV",
    "active": true
  },
  {
    "id": "u040",
    "name": "Nestor Escobar Ramos",
    "email": "nestor.escobar",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar de Servicios Generales",
    "avatar": "NE",
    "active": true
  },
  {
    "id": "u041",
    "name": "Oscar Ruben Paez Nuñez",
    "email": "oscar.paez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Auxiliar de Servicios Generales Confinamiento",
    "avatar": "OP",
    "active": true
  },
  {
    "id": "u042",
    "name": "Tito Tomas",
    "email": "tito.tomas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tractorista Confinamiento",
    "avatar": "TT",
    "active": true
  },
  {
    "id": "u043",
    "name": "Isaias Basilio Riquelme Coronel",
    "email": "isaias.riquelme",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Capataz Confinamento",
    "avatar": "IR",
    "active": true
  },
  {
    "id": "u044",
    "name": "Cesar Arguello Gonzalez",
    "email": "cesar.arguello",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero Ronda Confinamento",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u045",
    "name": "Heriberto Moral Gimenez",
    "email": "heriberto.moral",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero Ronda Confinamento",
    "avatar": "HM",
    "active": true
  },
  {
    "id": "u046",
    "name": "Marcelo Ivan Pimentel",
    "email": "marcelo.pimentel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero Ronda Confinamento",
    "avatar": "MP",
    "active": true
  },
  {
    "id": "u047",
    "name": "Fidel Coronel Villamayor",
    "email": "fidel.coronel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Palero Confinamiento",
    "avatar": "FC",
    "active": true
  },
  {
    "id": "u048",
    "name": "Francisco Arce",
    "email": "francisco.arce",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "FA",
    "active": true
  },
  {
    "id": "u049",
    "name": "Hugo Javier Florenciano",
    "email": "hugo.javier",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "HJ",
    "active": true
  },
  {
    "id": "u050",
    "name": "Julio Ariel Villamayor Fretez",
    "email": "julio.villamayor",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tractorista Confinamiento",
    "avatar": "JV",
    "active": true
  },
  {
    "id": "u051",
    "name": "Nery Paez",
    "email": "nery.paez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "NP",
    "active": true
  },
  {
    "id": "u052",
    "name": "Oscar David Candia Cañiza",
    "email": "oscar.candia",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "OC",
    "active": true
  },
  {
    "id": "u053",
    "name": "Richar Mendoza Ferreira",
    "email": "richar.mendoza",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "RM",
    "active": true
  },
  {
    "id": "u054",
    "name": "Victor Ramon Pereira",
    "email": "victor.ramon",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Tratador Confinamiento",
    "avatar": "VR",
    "active": true
  },
  {
    "id": "u055",
    "name": "Adolfina Bareiro",
    "email": "adolfina.bareiro",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Cocinera",
    "avatar": "AB",
    "active": true
  },
  {
    "id": "u056",
    "name": "Oscar Gabriel Penayo Cardozo",
    "email": "oscar.penayo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Portonero",
    "avatar": "OP",
    "active": true
  },
  {
    "id": "u057",
    "name": "Edgar Raul Gonzalez Ortiz",
    "email": "edgar.gonzalez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Portonero",
    "avatar": "EG",
    "active": true
  },
  {
    "id": "u058",
    "name": "Myrian Ysabel Bareiro Riquelme",
    "email": "myrian.bareiro",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Cocinera",
    "avatar": "MB",
    "active": true
  },
  {
    "id": "u059",
    "name": "Evaristo Ortigoza",
    "email": "evaristo.ortigoza",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Encargado Mantenimiento Plomeria, Cerca Elétrica, Casa",
    "avatar": "EO",
    "active": true
  },
  {
    "id": "u060",
    "name": "Arnaldo Vargas Larrea",
    "email": "arnaldo.vargas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Mantenimiento Plomeria, Cerca Elétrica, Casa",
    "avatar": "AV",
    "active": true
  },
  {
    "id": "u061",
    "name": "Silvio Ciriaco Salinas",
    "email": "silvio.salinas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Ayudante Mantenimiento Plomeria, Cerca Elétrica, Casa",
    "avatar": "SS",
    "active": true
  },
  {
    "id": "u062",
    "name": "Juan Diego Paranderi Monges",
    "email": "juan.paranderi",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Supervisor Recria",
    "avatar": "JP",
    "active": true
  },
  {
    "id": "u063",
    "name": "Eduardo Antonio Cuevas Urbieta",
    "email": "eduardo.cuevas",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Capataz General",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u064",
    "name": "Evaristo Ocampo Vega",
    "email": "evaristo.ocampo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Salgador",
    "avatar": "EO",
    "active": true
  },
  {
    "id": "u065",
    "name": "Richard Daniel Vento Larrea",
    "email": "richard.vento",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "RV",
    "active": true
  },
  {
    "id": "u066",
    "name": "Antonio Ceveriano Dominguez Valdez",
    "email": "antonio.dominguez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "AD",
    "active": true
  },
  {
    "id": "u067",
    "name": "Emigdio Carballo Arce",
    "email": "emigdio.carballo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u068",
    "name": "Luciano Aguirre Osorio",
    "email": "luciano.aguirre",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "LA",
    "active": true
  },
  {
    "id": "u069",
    "name": "Luciano Vargas Larrea",
    "email": "luciano.vargas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "LV",
    "active": true
  },
  {
    "id": "u070",
    "name": "Nestor Emigdio Cuevas Urbieta",
    "email": "nestor.cuevas",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Capataz Retiro",
    "avatar": "NC",
    "active": true
  },
  {
    "id": "u071",
    "name": "Obidio Javier Ledesma Martinez",
    "email": "obidio.ledesma",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "OL",
    "active": true
  },
  {
    "id": "u072",
    "name": "Pancracio Arguello",
    "email": "pancracio.arguello",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "PA",
    "active": true
  },
  {
    "id": "u073",
    "name": "Reginaldo de Almeida Reis",
    "email": "reginaldo.de",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ypoti",
    "position": "Capataz de Retiro",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u074",
    "name": "Richard Vento",
    "email": "richard.vento2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero",
    "avatar": "RV",
    "active": true
  },
  {
    "id": "u075",
    "name": "Renato Vera Nogueira",
    "email": "renato.vera",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero Retiro",
    "avatar": "RV",
    "active": true
  },
  {
    "id": "u076",
    "name": "Narlo Arístides Zorrilla Paredes",
    "email": "narlo.zorrilla",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Campero Retiro",
    "avatar": "NZ",
    "active": true
  },
  {
    "id": "u077",
    "name": "Cristian Larrea",
    "email": "cristian.larrea",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ypoti",
    "position": "Compostaje",
    "avatar": "CL",
    "active": true
  },
  {
    "id": "u078",
    "name": "Eliseo Cabañas Lopez",
    "email": "eliseo.cabanas",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Oro Verde",
    "position": "Capataz",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u079",
    "name": "Freddy Gomez",
    "email": "freddy.gomez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Oro Verde",
    "position": "Seguridad",
    "avatar": "FG",
    "active": true
  },
  {
    "id": "u080",
    "name": "David Javier Aquino Bogado",
    "email": "david.aquino",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Oro Verde",
    "position": "Campero",
    "avatar": "DA",
    "active": true
  },
  {
    "id": "u081",
    "name": "Henrique Caceres",
    "email": "henrique.caceres",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Asistente Adm Estancia",
    "avatar": "HC",
    "active": true
  },
  {
    "id": "u082",
    "name": "Elias Duarte",
    "email": "elias.duarte",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Tratorista",
    "avatar": "ED",
    "active": true
  },
  {
    "id": "u083",
    "name": "Eliodoro Famoso",
    "email": "eliodoro.famoso",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Santa Maria",
    "position": "Capataz Retiro",
    "avatar": "EF",
    "active": true
  },
  {
    "id": "u084",
    "name": "Virgilio Ortigoza",
    "email": "virgilio.ortigoza",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Santa Maria",
    "position": "Capataz",
    "avatar": "VO",
    "active": true
  },
  {
    "id": "u085",
    "name": "Abel Cabanas",
    "email": "abel.cabanas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Campero",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u086",
    "name": "Agenor Centurion",
    "email": "agenor.centurion",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Campero",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u087",
    "name": "Bruno Antonio",
    "email": "bruno.antonio",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Campero",
    "avatar": "BA",
    "active": true
  },
  {
    "id": "u088",
    "name": "Renato Flores",
    "email": "renato.flores",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Campero",
    "avatar": "RF",
    "active": true
  },
  {
    "id": "u089",
    "name": "Nilson Centurion",
    "email": "nilson.centurion",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Menor Campero",
    "avatar": "NC",
    "active": true
  },
  {
    "id": "u090",
    "name": "Roque Maciel",
    "email": "roque.maciel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Ayudante Tratorista",
    "avatar": "RM",
    "active": true
  },
  {
    "id": "u091",
    "name": "Cristian Moreno",
    "email": "cristian.moreno",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Maria",
    "position": "Campero",
    "avatar": "CM",
    "active": true
  },
  {
    "id": "u092",
    "name": "Cristian Martinez",
    "email": "cristian.martinez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Tractorista",
    "avatar": "CM",
    "active": true
  },
  {
    "id": "u093",
    "name": "Nilton Cesar Dornelis",
    "email": "nilton.dornelis",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Cielo Azul",
    "position": "Capataz",
    "avatar": "ND",
    "active": true
  },
  {
    "id": "u094",
    "name": "Ricardo Ramirez",
    "email": "ricardo.ramirez",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Cielo Azul",
    "position": "Capataz Retiro",
    "avatar": "RR",
    "active": true
  },
  {
    "id": "u095",
    "name": "Pablo Gonzales",
    "email": "pablo.gonzales",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Ayudante Tractorista",
    "avatar": "PG",
    "active": true
  },
  {
    "id": "u096",
    "name": "Jonathan Ramirez Cuba",
    "email": "jonathan.ramirez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Campero",
    "avatar": "JR",
    "active": true
  },
  {
    "id": "u097",
    "name": "Silvio Gabriel Villalba Martinez",
    "email": "silvio.gabriel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Campero",
    "avatar": "SG",
    "active": true
  },
  {
    "id": "u098",
    "name": "Blas Fernandez",
    "email": "blas.fernandez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Campero",
    "avatar": "BF",
    "active": true
  },
  {
    "id": "u099",
    "name": "Derliz Lopez",
    "email": "derliz.lopez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Campero",
    "avatar": "DL",
    "active": true
  },
  {
    "id": "u100",
    "name": "Fabricio Concepcion Dornelis",
    "email": "fabricio.concepcion",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cielo Azul",
    "position": "Campero",
    "avatar": "FC",
    "active": true
  },
  {
    "id": "u101",
    "name": "Ramon Sosa",
    "email": "ramon.sosa",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Asistente Adm Estancia",
    "avatar": "RS",
    "active": true
  },
  {
    "id": "u102",
    "name": "Vidal Acosta",
    "email": "vidal.acosta",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Ybypora",
    "position": "Capataz",
    "avatar": "VA",
    "active": true
  },
  {
    "id": "u103",
    "name": "Daniel Acosta",
    "email": "daniel.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ybypora",
    "position": "Campero",
    "avatar": "DA",
    "active": true
  },
  {
    "id": "u104",
    "name": "German Rodas Añazco",
    "email": "german.rodas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ybypora",
    "position": "Campero",
    "avatar": "GR",
    "active": true
  },
  {
    "id": "u105",
    "name": "Manuel Acosta Franco",
    "email": "manuel.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ybypora",
    "position": "Campero",
    "avatar": "MA",
    "active": true
  },
  {
    "id": "u106",
    "name": "Sanabria de Los Santos",
    "email": "sanabria.de",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ybypora",
    "position": "Campero",
    "avatar": "SD",
    "active": true
  },
  {
    "id": "u107",
    "name": "Victor Acosta",
    "email": "victor.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Ybypora",
    "position": "Campero",
    "avatar": "VA",
    "active": true
  },
  {
    "id": "u108",
    "name": "Candelario Lopez",
    "email": "candelario.lopez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Mantenimiento Casa Patronal",
    "avatar": "CL",
    "active": true
  },
  {
    "id": "u109",
    "name": "Demesio Romero",
    "email": "demesio.romero",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Mantenimiento Plomeria, Carpinteria y Alambrado",
    "avatar": "DR",
    "active": true
  },
  {
    "id": "u110",
    "name": "Eladio Romero",
    "email": "eladio.romero",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Cerro Memby",
    "position": "Jefe Fábrica",
    "avatar": "ER",
    "active": true
  },
  {
    "id": "u111",
    "name": "Josival Francisco Ferreira",
    "email": "josival.ferreira",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Playero",
    "avatar": "JF",
    "active": true
  },
  {
    "id": "u112",
    "name": "Leandro da Silva Souza",
    "email": "leandro.da",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Cerro Memby",
    "position": "Capataz",
    "avatar": "LD",
    "active": true
  },
  {
    "id": "u113",
    "name": "Narciso Martinez Vera",
    "email": "narciso.martinez",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Cerro Memby",
    "position": "Capataz Retiro",
    "avatar": "NM",
    "active": true
  },
  {
    "id": "u114",
    "name": "Rolando Lopez",
    "email": "rolando.lopez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Tractorista",
    "avatar": "RL",
    "active": true
  },
  {
    "id": "u115",
    "name": "Bruno Romero",
    "email": "bruno.romero",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Ayudante Fábrica",
    "avatar": "BR",
    "active": true
  },
  {
    "id": "u116",
    "name": "Carlos Eduardo Figueira Alves",
    "email": "carlos.figueira",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Campero",
    "avatar": "CF",
    "active": true
  },
  {
    "id": "u117",
    "name": "Leonel da Silva Lopez",
    "email": "leonel.da",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Cerro Memby",
    "position": "Campero",
    "avatar": "LD",
    "active": true
  },
  {
    "id": "u118",
    "name": "Isidro Villalba",
    "email": "isidro.villalba",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Clara",
    "position": "Tractorista",
    "avatar": "IV",
    "active": true
  },
  {
    "id": "u119",
    "name": "Pedro Alvarez",
    "email": "pedro.alvarez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Santa Clara",
    "position": "Seguridad",
    "avatar": "PA",
    "active": true
  },
  {
    "id": "u120",
    "name": "Ever Cristaldo",
    "email": "ever.cristaldo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Mantenimiento y Servicios Generales",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u121",
    "name": "Hector Irala",
    "email": "hector.irala",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "Lusipar",
    "position": "Capataz",
    "avatar": "HI",
    "active": true
  },
  {
    "id": "u122",
    "name": "Clotildo Acosta",
    "email": "clotildo.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Campero",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u123",
    "name": "Elias Duartes",
    "email": "elias.duartes",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Campero",
    "avatar": "ED",
    "active": true
  },
  {
    "id": "u124",
    "name": "Nelson Cristado",
    "email": "nelson.cristado",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Campero",
    "avatar": "NC",
    "active": true
  },
  {
    "id": "u125",
    "name": "Nicolas Molina",
    "email": "nicolas.molina",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Campero",
    "avatar": "NM",
    "active": true
  },
  {
    "id": "u126",
    "name": "Victor Vera",
    "email": "victor.vera",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Campero",
    "avatar": "VV",
    "active": true
  },
  {
    "id": "u127",
    "name": "Epifanio Benitez",
    "email": "epifanio.benitez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Auxiliar Tractorista",
    "avatar": "EB",
    "active": true
  },
  {
    "id": "u128",
    "name": "Fidel Benitez",
    "email": "fidel.benitez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Tractorista",
    "avatar": "FB",
    "active": true
  },
  {
    "id": "u129",
    "name": "Ramon Ojeda",
    "email": "ramon.ojeda",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "Lusipar",
    "position": "Tractorista",
    "avatar": "RO",
    "active": true
  },
  {
    "id": "u130",
    "name": "Gabriel Moller",
    "email": "gabriel",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente Adminsitrativo",
    "avatar": "GM",
    "active": true
  },
  {
    "id": "u131",
    "name": "Anahi Raquel Aguirre de Leiva",
    "email": "anahi",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Supervisora Administrativa",
    "avatar": "AA",
    "active": true
  },
  {
    "id": "u132",
    "name": "Alex Samudio",
    "email": "alex.samudio",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Servicios Generales",
    "avatar": "AS",
    "active": true
  },
  {
    "id": "u133",
    "name": "Ana Karina Ticianelli Moller",
    "email": "ana.karina",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente Financeira",
    "avatar": "AT",
    "active": true
  },
  {
    "id": "u134",
    "name": "Kelin Bradshav",
    "email": "kelin",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Analista de Pagos",
    "avatar": "KB",
    "active": true
  },
  {
    "id": "u135",
    "name": "Lucas Enrico",
    "email": "lucas.enrico",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente de Estrategia Financeira",
    "avatar": "LE",
    "active": true
  },
  {
    "id": "u136",
    "name": "Leticia Gonzalez",
    "email": "leticia.gonzalez",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Supervisora Contable",
    "avatar": "LG",
    "active": true
  },
  {
    "id": "u137",
    "name": "Freddy Prodato",
    "email": "freddy.prodato",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "(reemplazo Leticia)",
    "avatar": "FP",
    "active": true
  },
  {
    "id": "u138",
    "name": "Renzo Miltos",
    "email": "renzo.miltos",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Auxiliar Contable",
    "avatar": "RM",
    "active": true
  },
  {
    "id": "u139",
    "name": "Guillermo Caceres",
    "email": "guillermo",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Auxiliar Contable",
    "avatar": "GC",
    "active": true
  },
  {
    "id": "u140",
    "name": "Paola Rios",
    "email": "paola.rios",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Auxiliar Contable",
    "avatar": "PR",
    "active": true
  },
  {
    "id": "u141",
    "name": "Eduardo Ivan Olivetti Gaona",
    "email": "eduardo.olivetti",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Certificador",
    "avatar": "EO",
    "active": true
  },
  {
    "id": "u142",
    "name": "Guillermo Encina",
    "email": "guillermo.encina",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Empleado",
    "avatar": "GE",
    "active": true
  },
  {
    "id": "u143",
    "name": "Adalberto Cuevas",
    "email": "adalberto.cuevas",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u144",
    "name": "Albino Lopez",
    "email": "albino.lopez",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "AL",
    "active": true
  },
  {
    "id": "u145",
    "name": "Alex Vega",
    "email": "alex.vega",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "AV",
    "active": true
  },
  {
    "id": "u146",
    "name": "Alexis Ramon Gomez",
    "email": "alexis.ramon",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "AR",
    "active": true
  },
  {
    "id": "u147",
    "name": "Alvaro Cuevas Urbieta",
    "email": "alvaro.cuevas2",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente de Pasto",
    "avatar": "AC",
    "active": true
  },
  {
    "id": "u148",
    "name": "Angel Loreto Paez Caceres",
    "email": "angel.loreto",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Repartidor de Sal",
    "avatar": "AL",
    "active": true
  },
  {
    "id": "u149",
    "name": "Candido Ocampos Ovelar",
    "email": "candido.ocampos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Seguridad",
    "avatar": "CO",
    "active": true
  },
  {
    "id": "u150",
    "name": "Carlos Eduardo",
    "email": "carlos.eduardo",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "CE",
    "active": true
  },
  {
    "id": "u151",
    "name": "Carlos Eduardo Alves",
    "email": "carlos.alves",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u152",
    "name": "Celso Riquelme",
    "email": "celso.riquelme",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ayudante Fabrica",
    "avatar": "CR",
    "active": true
  },
  {
    "id": "u153",
    "name": "Celso Riquelmo",
    "email": "celso.riquelmo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ayudante Fabrica",
    "avatar": "CR",
    "active": true
  },
  {
    "id": "u154",
    "name": "Claudia Acosta",
    "email": "claudia.acosta",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Servicio Domestico y Cocinera",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u155",
    "name": "Claudia Acosta Noguera",
    "email": "claudia.acosta2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Cocinera",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u156",
    "name": "Clotildo Acosta Noguera",
    "email": "clotildo.acosta2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "CA",
    "active": true
  },
  {
    "id": "u157",
    "name": "Cristian Damian Sosa Benitez",
    "email": "cristian.damian",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder de Limpieza",
    "avatar": "CD",
    "active": true
  },
  {
    "id": "u158",
    "name": "Cristian Larrea Arevalos",
    "email": "cristian.larrea2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tractorista",
    "avatar": "CL",
    "active": true
  },
  {
    "id": "u159",
    "name": "Cristobal Coronel",
    "email": "cristobal.coronel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Mecanico",
    "avatar": "CC",
    "active": true
  },
  {
    "id": "u160",
    "name": "Del Rosario Paredes",
    "email": "del.paredes",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "DP",
    "active": true
  },
  {
    "id": "u161",
    "name": "Edgar",
    "email": "edgar.x",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder Mantenimiento",
    "avatar": "EX",
    "active": true
  },
  {
    "id": "u162",
    "name": "Eduardo Cuevas",
    "email": "eduardo.cuevas2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz General",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u163",
    "name": "Efigenio Vargas",
    "email": "efigenio.vargas",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ayudante Fabrica",
    "avatar": "EV",
    "active": true
  },
  {
    "id": "u164",
    "name": "Efigenio Vargas Larrea",
    "email": "efigenio.vargas2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Molinador",
    "avatar": "EV",
    "active": true
  },
  {
    "id": "u165",
    "name": "Emerenciano Riquelme",
    "email": "emerenciano.riquelme2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Fabrica",
    "avatar": "ER",
    "active": true
  },
  {
    "id": "u166",
    "name": "Emerenciano Riquelme Coronel",
    "email": "emerenciano.riquelme3",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder Fabrica",
    "avatar": "ER",
    "active": true
  },
  {
    "id": "u167",
    "name": "Epifanio Miranda",
    "email": "epifanio.miranda",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ayudante Seguridad",
    "avatar": "EM",
    "active": true
  },
  {
    "id": "u168",
    "name": "Epinafio Benitez",
    "email": "epinafio.benitez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar Tractorista",
    "avatar": "EB",
    "active": true
  },
  {
    "id": "u169",
    "name": "Erson Bruno Paredes",
    "email": "erson.paredes",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "EP",
    "active": true
  },
  {
    "id": "u170",
    "name": "Eumelio Fernandez",
    "email": "eumelio.fernandez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "EF",
    "active": true
  },
  {
    "id": "u171",
    "name": "Eumelio Villamayor Fernandez",
    "email": "eumelio.villamayor",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tractorista",
    "avatar": "EV",
    "active": true
  },
  {
    "id": "u172",
    "name": "Evaristo Ortigoza Gimenez",
    "email": "evaristo.ortigoza2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder Mantenimiento",
    "avatar": "EO",
    "active": true
  },
  {
    "id": "u173",
    "name": "Ever Leonor Cristaldo Ricardi",
    "email": "ever.cristaldo2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder Mantenimiento",
    "avatar": "EC",
    "active": true
  },
  {
    "id": "u174",
    "name": "Favio Ramon Gabilan",
    "email": "favio.ramon",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar de Mantenimiento",
    "avatar": "FR",
    "active": true
  },
  {
    "id": "u175",
    "name": "Felipe Villalba",
    "email": "felipe.villalba",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "FV",
    "active": true
  },
  {
    "id": "u176",
    "name": "Fernando da Silva",
    "email": "fernando.da",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "FD",
    "active": true
  },
  {
    "id": "u177",
    "name": "Fernando Duarte",
    "email": "fernando.duarte",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Administrativo",
    "avatar": "FD",
    "active": true
  },
  {
    "id": "u178",
    "name": "Fernando Rafael Dima Bareiro",
    "email": "fernando.dima",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar de Mantenimiento",
    "avatar": "FD",
    "active": true
  },
  {
    "id": "u179",
    "name": "Fidel Coronel",
    "email": "fidel.coronel2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Palero",
    "avatar": "FC",
    "active": true
  },
  {
    "id": "u180",
    "name": "Floriano Britez Mendoza",
    "email": "floriano.britez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "FB",
    "active": true
  },
  {
    "id": "u181",
    "name": "Freddy Mariano",
    "email": "freddy.mariano",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Seguridad",
    "avatar": "FM",
    "active": true
  },
  {
    "id": "u182",
    "name": "Fredy Larrea Arevalos",
    "email": "fredy.larrea",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar de Mantenimiento",
    "avatar": "FL",
    "active": true
  },
  {
    "id": "u183",
    "name": "Gimenez Gonzalez Hugo Miguel",
    "email": "gimenez.hugo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "GH",
    "active": true
  },
  {
    "id": "u184",
    "name": "Hector Irala Figueredo",
    "email": "hector.irala2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "HI",
    "active": true
  },
  {
    "id": "u185",
    "name": "Herminio Aquino",
    "email": "herminio.aquino2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Palero",
    "avatar": "HA",
    "active": true
  },
  {
    "id": "u186",
    "name": "Hernan Hermogenes Britez Baez",
    "email": "hernan.britez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "HB",
    "active": true
  },
  {
    "id": "u187",
    "name": "Hugo Coronel",
    "email": "hugo.coronel",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "HC",
    "active": true
  },
  {
    "id": "u188",
    "name": "Hugo Florenciano",
    "email": "hugo.florenciano",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "HF",
    "active": true
  },
  {
    "id": "u189",
    "name": "Hugo Gimenez",
    "email": "hugo.gimenez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ronda Sanitaria",
    "avatar": "HG",
    "active": true
  },
  {
    "id": "u190",
    "name": "Hugo Riquelme Coronel",
    "email": "hugo.riquelme",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "HR",
    "active": true
  },
  {
    "id": "u191",
    "name": "Hugo David Riquelme Coronel",
    "email": "hugo.riquelme2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "HR",
    "active": true
  },
  {
    "id": "u192",
    "name": "Hugo Javier Florenciano Arevalos",
    "email": "hugo.florenciano2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tratador",
    "avatar": "HF",
    "active": true
  },
  {
    "id": "u193",
    "name": "Hugo Miguel Gimenez Gonzalez",
    "email": "hugo.gimenez2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "HG",
    "active": true
  },
  {
    "id": "u194",
    "name": "Irio Cohene",
    "email": "irio.cohene",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "IC",
    "active": true
  },
  {
    "id": "u195",
    "name": "Irio Freisleben Cohene",
    "email": "irio.freisleben",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "IF",
    "active": true
  },
  {
    "id": "u196",
    "name": "Jhovanny Bareiro",
    "email": "jhovanny.bareiro",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "JB",
    "active": true
  },
  {
    "id": "u197",
    "name": "Juan Aquino",
    "email": "juan.aquino",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Surpevisor Confinamento",
    "avatar": "JA",
    "active": true
  },
  {
    "id": "u198",
    "name": "Juan Gonzales",
    "email": "juan.gonzales",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Encargado Confinamiento",
    "avatar": "JG",
    "active": true
  },
  {
    "id": "u199",
    "name": "Juan Aquino Gonzales",
    "email": "juan.gonzales2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar Fabrica",
    "avatar": "JG",
    "active": true
  },
  {
    "id": "u200",
    "name": "Justimiano Carreras",
    "email": "justimiano.carreras",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Portonero Nucleo 6",
    "avatar": "JC",
    "active": true
  },
  {
    "id": "u201",
    "name": "Lisandro Espinoza",
    "email": "lisandro.espinoza",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tractorista",
    "avatar": "LE",
    "active": true
  },
  {
    "id": "u202",
    "name": "Manuel Duarte",
    "email": "manuel.duarte",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "MD",
    "active": true
  },
  {
    "id": "u203",
    "name": "Mateo Caballero",
    "email": "mateo.caballero",
    "password": "ypoti2026",
    "role": "comprador",
    "establishment": "General",
    "position": "Contabilidad",
    "avatar": "MC",
    "active": true
  },
  {
    "id": "u204",
    "name": "Matias Alves",
    "email": "matias.alves",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "MA",
    "active": true
  },
  {
    "id": "u205",
    "name": "Mauricio Martinez",
    "email": "mauricio.martinez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "MM",
    "active": true
  },
  {
    "id": "u206",
    "name": "Mauricio Moller",
    "email": "mauricio",
    "password": "ypoti2026",
    "role": "admin",
    "establishment": "General",
    "position": "Presidente",
    "avatar": "MM",
    "active": true
  },
  {
    "id": "u207",
    "name": "Meliano Duarte",
    "email": "meliano.duarte",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "MD",
    "active": true
  },
  {
    "id": "u208",
    "name": "Meliano Duarte Morinigo",
    "email": "meliano.duarte2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Líder Ronda Sanitaria",
    "avatar": "MD",
    "active": true
  },
  {
    "id": "u209",
    "name": "Milder Medina",
    "email": "milder.medina",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "MM",
    "active": true
  },
  {
    "id": "u210",
    "name": "Nelson Morel",
    "email": "nelson.morel",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz Retiro Sur",
    "avatar": "NM",
    "active": true
  },
  {
    "id": "u211",
    "name": "Nelson Morel Vega",
    "email": "nelson.morel2",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "NM",
    "active": true
  },
  {
    "id": "u212",
    "name": "Nelson Tomas Cristaldo Ricardi",
    "email": "nelson.cristaldo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "NC",
    "active": true
  },
  {
    "id": "u213",
    "name": "Nery Paez",
    "email": "nery.paez2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Molinador de Heno",
    "avatar": "NP",
    "active": true
  },
  {
    "id": "u214",
    "name": "Oscar Paez",
    "email": "oscar.paez2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Lavador Pileta",
    "avatar": "OP",
    "active": true
  },
  {
    "id": "u215",
    "name": "Oscar Adan Carmona Villalba",
    "email": "oscar.carmona",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar Fabrica",
    "avatar": "OC",
    "active": true
  },
  {
    "id": "u216",
    "name": "Oscar David Paredes",
    "email": "oscar.paredes",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "OP",
    "active": true
  },
  {
    "id": "u217",
    "name": "Pablo de Moraes de Silva",
    "email": "pablo.de",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz General",
    "avatar": "PD",
    "active": true
  },
  {
    "id": "u218",
    "name": "Pedro Blanco Nolasco",
    "email": "pedro.blanco",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "PB",
    "active": true
  },
  {
    "id": "u219",
    "name": "Pedro Nolasco",
    "email": "pedro.nolasco",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "PN",
    "active": true
  },
  {
    "id": "u220",
    "name": "Rafael Dima",
    "email": "rafael.dima",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Cuidador",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u221",
    "name": "Rafael Dima Minela",
    "email": "rafael.dima2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Seguridad",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u222",
    "name": "Ramon Sosa Oliveira",
    "email": "ramon.sosa2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "RS",
    "active": true
  },
  {
    "id": "u223",
    "name": "Ramon Ojeda Ojeda",
    "email": "ramon.ojeda2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Tractorista",
    "avatar": "RO",
    "active": true
  },
  {
    "id": "u224",
    "name": "Ranulfo Martinez",
    "email": "ranulfo.martinez",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Capataz",
    "avatar": "RM",
    "active": true
  },
  {
    "id": "u225",
    "name": "Ricardo Arguello",
    "email": "ricardo.arguello",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Ayudante Ronda Sanitaria",
    "avatar": "RA",
    "active": true
  },
  {
    "id": "u226",
    "name": "Ricardo Cardozo Curtido",
    "email": "ricardo.cardozo",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "RC",
    "active": true
  },
  {
    "id": "u227",
    "name": "Ricardo Dos Santos Soares",
    "email": "ricardo.dos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Auxiliar Ronda Sanitária",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u228",
    "name": "Ricardo Soares",
    "email": "ricardo.soares",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "RS",
    "active": true
  },
  {
    "id": "u229",
    "name": "Richard David Silva Insfran",
    "email": "richard.silva",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "RS",
    "active": true
  },
  {
    "id": "u230",
    "name": "Robert Salazar",
    "email": "robert.salazar",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Palero",
    "avatar": "RS",
    "active": true
  },
  {
    "id": "u231",
    "name": "Rodolfo Arevalos",
    "email": "rodolfo.arevalos",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Palero",
    "avatar": "RA",
    "active": true
  },
  {
    "id": "u232",
    "name": "Rodolfo Florenciano",
    "email": "rodolfo.florenciano",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Palero",
    "avatar": "RF",
    "active": true
  },
  {
    "id": "u233",
    "name": "Rodolfo Florenciano Arevalos",
    "email": "rodolfo.florenciano2",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Molinador",
    "avatar": "RF",
    "active": true
  },
  {
    "id": "u234",
    "name": "Rodrigo Dosanto Gayozo",
    "email": "rodrigo.dosanto",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Responsable Confinamiento",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u235",
    "name": "Rolando Benitez Gonzalez",
    "email": "rolando.benitez",
    "password": "ypoti2026",
    "role": "lider",
    "establishment": "General",
    "position": "Palero y Jefe de Maquinas",
    "avatar": "RB",
    "active": true
  },
  {
    "id": "u236",
    "name": "Rosevaldo Dos Santo Bonfauche",
    "email": "rosevaldo.dos",
    "password": "ypoti2026",
    "role": "gerente",
    "establishment": "General",
    "position": "Gerente",
    "avatar": "RD",
    "active": true
  },
  {
    "id": "u237",
    "name": "Rufino Gomez",
    "email": "rufino.gomez",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "RG",
    "active": true
  },
  {
    "id": "u238",
    "name": "Victor Dima",
    "email": "victor.dima",
    "password": "ypoti2026",
    "role": "solicitante",
    "establishment": "General",
    "position": "Campero",
    "avatar": "VD",
    "active": true
  }
];
