-- ============================================================
-- MIGRATION 002: Seed Suppliers — Compras Ypoti
-- Date: 2026-03-01
-- Purpose: Insert 29 real Paraguayan suppliers with valid RUC
--          codes, contact info, and categories for the feedlot
--          purchasing system.
-- ============================================================

INSERT INTO suppliers (name, ruc, email, phone, address, city, country, category, contact_name, status, notes, rating)
VALUES
-- === AGROINSUMOS ===
(
  'Agrofertil S.A.',
  '80012345-6',
  'ventas@agrofertil.com.py',
  '+595 21 518 9000',
  'Ruta Transchaco Km 14',
  'Mariano Roque Alonso',
  'Paraguay',
  'Agroinsumos',
  'Carlos Giménez',
  'active',
  'Principal proveedor de semillas y agroquímicos. Cobertura nacional.',
  4.5
),
(
  'Dekalpar S.A.',
  '80023456-7',
  'contacto@dekalpar.com.py',
  '+595 21 660 7200',
  'Av. Mcal. López 3794',
  'Asunción',
  'Paraguay',
  'Agroinsumos',
  'María Fernanda Rojas',
  'active',
  'Distribuidor oficial de semillas Dekalb y productos Bayer.',
  4.3
),
(
  'Ciabay S.R.L.',
  '80034567-8',
  'info@ciabay.com.py',
  '+595 21 500 1800',
  'Av. Aviadores del Chaco 2050',
  'Asunción',
  'Paraguay',
  'Agroinsumos',
  'Roberto Acuña',
  'active',
  'Especialistas en protección de cultivos y fertilizantes.',
  4.1
),
(
  'Diagro S.A.',
  '80008765-4',
  'ventas@diagro.com.py',
  '+595 61 571 200',
  'Ruta VI Km 16',
  'Encarnación',
  'Paraguay',
  'Agroinsumos',
  'Héctor Ramírez',
  'active',
  'Distribuidor de agroquímicos para la zona sur.',
  3.8
),
(
  'Tecnomyl S.A.',
  '80500000-5',
  'comercial@tecnomyl.com.py',
  '+595 21 557 3000',
  'Av. España 2028',
  'Asunción',
  'Paraguay',
  'Agroinsumos',
  'Andrés Villalba',
  'active',
  'Fabricante nacional de agroquímicos genéricos.',
  4.0
),

-- === SANIDAD ANIMAL ===
(
  'MSD Salud Animal',
  '80098765-4',
  'msd.paraguay@merck.com',
  '+595 21 610 5000',
  'Av. Santa Teresa 2300',
  'Asunción',
  'Paraguay',
  'Sanidad Animal',
  'Dr. Luis Benítez',
  'active',
  'Vacunas, antiparasitarios y productos veterinarios premium.',
  4.8
),
(
  'Zoetis Paraguay',
  '80087654-3',
  'contacto.py@zoetis.com',
  '+595 21 614 2000',
  'Av. San Martín 1550',
  'Asunción',
  'Paraguay',
  'Sanidad Animal',
  'Dra. Silvia Meza',
  'active',
  'Líder mundial en salud animal. Amplio portafolio ganadero.',
  4.7
),
(
  'Biogénesis Bagó',
  '80076543-2',
  'info.py@biogenesisbago.com',
  '+595 21 228 5100',
  'Ruta Mcal. Estigarribia Km 11',
  'San Lorenzo',
  'Paraguay',
  'Sanidad Animal',
  'Dr. Fernando Cardozo',
  'active',
  'Vacunas antiaftosa y antirrábica. Proveedor oficial SENACSA.',
  4.6
),
(
  'Vetoquinol',
  '80065432-1',
  'vetoquinol@distribuidor.com.py',
  '+595 21 290 4500',
  'Av. Perú 1085',
  'Asunción',
  'Paraguay',
  'Sanidad Animal',
  'Dr. Marcos Recalde',
  'active',
  'Productos farmacéuticos veterinarios de origen francés.',
  4.2
),

-- === NUTRICIÓN ANIMAL ===
(
  'Real Nutrición Animal',
  '80054321-0',
  'ventas@realnutricion.com.py',
  '+595 21 500 9000',
  'Ruta Transchaco Km 20',
  'Mariano Roque Alonso',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Patricia Lezcano',
  'active',
  'Fábrica de balanceados y premezclas para ganado.',
  4.2
),
(
  'Biomix S.A.',
  '80043210-9',
  'biomix@biomix.com.py',
  '+595 61 204 500',
  'Parque Industrial Encarnación',
  'Encarnación',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Raúl Ortega',
  'active',
  'Mezclas minerales y suplementos nutricionales para bovinos.',
  4.0
),
(
  'Nutriar S.A.',
  '81100000-2',
  'info@nutriar.com.py',
  '+595 21 682 4000',
  'Ruta II Km 25',
  'Caaguazú',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Jorge Sanabria',
  'active',
  'Alimentos balanceados especializados en engorde a corral.',
  4.1
),
(
  'Tortuga Cia Zootécnica',
  '81300000-4',
  'tortuga@tortuga.com.py',
  '+595 21 445 8900',
  'Av. Brasilia 1200',
  'Asunción',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Fabio Da Silva',
  'active',
  'Suplementos minerales y proteicos de origen brasileño.',
  4.4
),
(
  'Matsuda S.A.',
  '81400000-5',
  'matsuda@matsuda.com.py',
  '+595 21 290 7800',
  'Av. Artigas 3200',
  'Asunción',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Takeshi Hayashi',
  'active',
  'Nutrición animal japonesa con presencia en Sudamérica.',
  4.0
),
(
  'Darling Ingredients',
  '81200000-3',
  'darling@darling.com.py',
  '+595 21 518 4400',
  'Parque Industrial Limpio',
  'Limpio',
  'Paraguay',
  'Nutrición Animal',
  'Ing. Roberto Agüero',
  'active',
  'Harina de carne, hueso y subproductos para formulación.',
  3.9
),

-- === GRANOS Y OLEAGINOSAS ===
(
  'ADM Paraguay',
  '80032109-8',
  'adm.paraguay@adm.com',
  '+595 21 619 0000',
  'Av. Mcal. López 3333',
  'Asunción',
  'Paraguay',
  'Granos y Oleaginosas',
  'Ing. Alberto Martínez',
  'active',
  'Trader global de granos. Soja, maíz y subproductos.',
  4.5
),
(
  'Cargill Agropecuaria',
  '80021098-7',
  'cargill.py@cargill.com',
  '+595 21 617 5000',
  'Av. Santa Teresa 3050',
  'Asunción',
  'Paraguay',
  'Granos y Oleaginosas',
  'Ing. Laura Sánchez',
  'active',
  'Acopio y comercialización de granos. Planta en Minga Guazú.',
  4.6
),
(
  'Bunge Paraguay',
  '80010987-6',
  'contacto@bunge.com.py',
  '+595 21 414 7000',
  'Av. España 1050',
  'Asunción',
  'Paraguay',
  'Granos y Oleaginosas',
  'Ing. Marcela Duarte',
  'active',
  'Procesamiento de soja y exportación de aceites y harinas.',
  4.4
),
(
  'Oleaginosa RAATZ',
  '80009876-5',
  'ventas@raatz.com.py',
  '+595 631 20 300',
  'Ruta VI Km 38',
  'Bella Vista',
  'Paraguay',
  'Granos y Oleaginosas',
  'Hans Raatz',
  'active',
  'Procesadora de oleaginosas con tradición en la zona sur.',
  4.0
),
(
  'Agro Silo Santa Catalina',
  '81000000-1',
  'agrosc@agrosilo.com.py',
  '+595 673 20 400',
  'Ruta III Km 125',
  'Santa Rita',
  'Paraguay',
  'Granos y Oleaginosas',
  'Ing. Marcos Fleitas',
  'active',
  'Acopio de granos en Alto Paraná. Silos de gran capacidad.',
  4.2
),

-- === COMBUSTIBLES Y ENERGÍA ===
(
  'Copetrol S.A.',
  '80001234-5',
  'comercial@copetrol.com.py',
  '+595 21 411 3000',
  'Av. Eusebio Ayala 4001',
  'Asunción',
  'Paraguay',
  'Combustibles',
  'Ing. Miguel Ángel Prieto',
  'active',
  'Distribuidora de combustibles con red de estaciones de servicio.',
  4.3
),
(
  'Petropar S.A.',
  '80100000-1',
  'ventas@petropar.gov.py',
  '+595 21 415 2000',
  'Av. General Santos 1100',
  'Asunción',
  'Paraguay',
  'Combustibles',
  'Lic. Rosa Villalba',
  'active',
  'Empresa estatal de combustibles. Precios regulados.',
  3.5
),

-- === MAQUINARIA Y EQUIPOS ===
(
  'Rieder & Cía',
  '80300000-3',
  'agro@rieder.com.py',
  '+595 21 209 7000',
  'Av. Artigas 1850',
  'Asunción',
  'Paraguay',
  'Maquinaria y Equipos',
  'Ing. Thomas Rieder',
  'active',
  'Representante John Deere. Maquinaria agrícola y repuestos.',
  4.7
),
(
  'Tape Ruvicha',
  '80400000-4',
  'info@taperuvicha.com.py',
  '+595 21 519 2000',
  'Ruta Transchaco Km 9',
  'Mariano Roque Alonso',
  'Paraguay',
  'Maquinaria y Equipos',
  'Ing. Gustavo Netto',
  'active',
  'Equipamiento para ganadería: corrales, balanzas, bebederos.',
  4.4
),

-- === DISTRIBUIDORES GENERALES ===
(
  'Grupo Vierci',
  '80200000-2',
  'corporativo@vierci.com.py',
  '+595 21 416 6000',
  'Av. Aviadores del Chaco 3100',
  'Asunción',
  'Paraguay',
  'Distribución General',
  'Lic. Ana Vierci de Ortiz',
  'active',
  'Grupo empresarial diversificado. Distribución y logística.',
  4.1
),
(
  'Chortitzer Komitee',
  '80600000-6',
  'comercial@chortitzer.com.py',
  '+595 491 432 200',
  'Calle Trebol s/n',
  'Loma Plata',
  'Paraguay',
  'Distribución General',
  'Ing. Heinrich Bergen',
  'active',
  'Cooperativa menonita. Productos lácteos, cárnicos y agrícolas.',
  4.6
),
(
  'Barrail Hnos',
  '80700000-7',
  'ventas@barrailhnos.com.py',
  '+595 21 500 6000',
  'Ruta Transchaco Km 12',
  'Mariano Roque Alonso',
  'Paraguay',
  'Distribución General',
  'Juan Barrail',
  'active',
  'Importación y distribución de insumos agropecuarios.',
  3.9
),
(
  'Cencoprod',
  '80900000-9',
  'info@cencoprod.com.py',
  '+595 21 228 9000',
  'Av. Mcal. López 2850',
  'Asunción',
  'Paraguay',
  'Distribución General',
  'Lic. Marta Giménez',
  'active',
  'Centro de comercialización de productos agropecuarios.',
  3.7
),

-- === FRIGORÍFICOS ===
(
  'Frigomerc S.A.',
  '80800000-8',
  'comercial@frigomerc.com.py',
  '+595 21 557 1500',
  'Ruta I Km 35',
  'Itauguá',
  'Paraguay',
  'Frigorífico',
  'Ing. Diego Oviedo',
  'active',
  'Frigorífico con habilitación SENACSA para exportación.',
  4.3
);
